### ISSUE TITLE
Quickstart broke on Spacy example

### ISSUE THREAD

**Issue by RichardLitt** [HLasse/TextDescriptives#196]
At this line: ```nlp = spacy.load("en_core_web_sm")```

This is probably an issue on my end, but as it's in the quickstart section, there should be a way for me to know how to fix this without looking at Spacy's docs, or at least a link to the relevant section of their docs, I think.

```
➜  textdesc-test python3 test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    nlp = spacy.load("en_core_web_sm")
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/spacy/__init__.py", line 60, in load
    config=config,
  File "/Users/richard/Library/Python/3.7/lib/python/site-packages/spacy/util.py", line 439, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

**Comment by HLasse** [comment]
Thanks! I have added a line in the README in e9138b0
