### ISSUE TITLE
Fails for empty strings

### ISSUE THREAD

**Issue by LudvigOlsen** [HLasse/TextDescriptives#213]
## How to reproduce the behaviour

```python
import textdescriptives as td
strings = [""]
td.extract_metrics(text=strings, spacy_model="en_core_web_lg", metrics=None)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/textdescriptives/extractors.py", line 172, in extract_metrics
    return extract_df(docs)
           ^^^^^^^^^^^^^^^^
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/textdescriptives/extractors.py", line 107, in extract_df
    return pd.DataFrame(extract_dict(docs, metrics, include_text))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/textdescriptives/extractors.py", line 52, in extract_dict
    return [extract_dict(doc, metrics, include_text)[0] for doc in docs]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/textdescriptives/extractors.py", line 52, in <listcomp>
    return [extract_dict(doc, metrics, include_text)[0] for doc in docs]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/spacy/language.py", line 1574, in pipe
    for doc in docs:
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/spacy/util.py", line 1680, in _pipe
    for doc in docs:
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/spacy/util.py", line 1680, in _pipe
    for doc in docs:
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/spacy/util.py", line 1680, in _pipe
    for doc in docs:
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/spacy/util.py", line 1685, in _pipe
    error_handler(name, proc, [doc], e)
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/spacy/util.py", line 1689, in raise_error
    raise e
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/spacy/util.py", line 1682, in _pipe
    doc = proc(doc, **kwargs)  # type: ignore[call-arg]
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/textdescriptives/components/quality.py", line 562, in __call__
    self.set_quality(doc)
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/textdescriptives/components/quality.py", line 513, in set_quality
    doc._._quality = self.quality_setter(doc).dict()
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/textdescriptives/components/quality.py", line 478, in quality_setter
    value_oov = oov_ratio(span, self.vocab)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/au547627/miniforge3/envs/textdesc/lib/python3.11/site-packages/textdescriptives/components/quality.py", line 350, in oov_ratio
    return len([token for token in span if token.is_oov]) / len(span)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
ZeroDivisionError: division by zero
```

## Your Environment

* textdescriptives Version Used: 2.4.4
* Operating System: Mac m1 Monterey
* Python Version Used: 3.11.0

**Comment by LudvigOlsen** [comment]
We should handle empty strings as it seems like something that could easily happen in an automated system. Either by a) removing them, or b) first excluding them and then adding them back to the result as np.nan for all metrics, or c) raising an error. 

a) is the easiest but if the end user expect the same number of rows as they inputted, it's problematic.

b) is probably the best as you would maintain the number of rows in the output with the order matching the input. But this increases complexity of the code as you first have to exclude the empty strings, remember their index and then insert them in the output. Technically you just have to store the indices I guess, although insertion of multiple empty rows might be tricky?

c) would require the user to decide between a) and b) (and then implement it). Seems annoying. 

I would probably go with b 

Further, perhaps we should have a look at whether to add a check for the length of span in the calculation or just allow it to fail with zero-division?

**Comment by HLasse** [comment]
Completely agree that b is the way to go. We actually already have handling for this in all components except `quality` and `information_theory`. If a metric can't be calculated (e.g. because of empty string) we return `np.nan`.

@KennethEnevoldsen you know the code for those components the best - is this something you'd be able to take a look at?

**Comment by LudvigOlsen** [comment]
And add a unit test when you're at it @KennethEnevoldsen ;)

**Comment by KennethEnevoldsen** [comment]
🫡
